/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: ['./index.html', './src/ui/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                heading: ['Neuton', 'serif'],
                body: ['Satoshi', 'sans-serif'],
            },
            colors: {
                black: 'rgb(var(--color-black))',
                white: 'rgb(var(--color-white))',
                aoi: {
                    50: 'rgb(var(--color-aoi-50))',
                    100: 'rgb(var(--color-aoi-100))',
                    200: 'rgb(var(--color-aoi-200))',
                    300: 'rgb(var(--color-aoi-300))',
                    400: 'rgb(var(--color-aoi-400))',
                    500: 'rgb(var(--color-aoi-500))',
                    600: 'rgb(var(--color-aoi-600))',
                    700: 'rgb(var(--color-aoi-700))',
                    800: 'rgb(var(--color-aoi-800))',
                    900: 'rgb(var(--color-aoi-900))',
                    950: 'rgb(var(--color-aoi-950))',
                },
                sakura: {
                    50: 'rgb(var(--color-sakura-50))',
                    100: 'rgb(var(--color-sakura-100))',
                    200: 'rgb(var(--color-sakura-200))',
                    300: 'rgb(var(--color-sakura-300))',
                    400: 'rgb(var(--color-sakura-400))',
                    500: 'rgb(var(--color-sakura-500))',
                    600: 'rgb(var(--color-sakura-600))',
                    700: 'rgb(var(--color-sakura-700))',
                    800: 'rgb(var(--color-sakura-800))',
                    900: 'rgb(var(--color-sakura-900))',
                },
                kin: {
                    50: 'rgb(var(--color-kin-50))',
                    100: 'rgb(var(--color-kin-100))',
                    200: 'rgb(var(--color-kin-200))',
                    300: 'rgb(var(--color-kin-300))',
                    400: 'rgb(var(--color-kin-400))',
                    500: 'rgb(var(--color-kin-500))',
                    600: 'rgb(var(--color-kin-600))',
                    700: 'rgb(var(--color-kin-700))',
                    800: 'rgb(var(--color-kin-800))',
                    900: 'rgb(var(--color-kin-900))',
                },
                tetsu: {
                    50: 'rgb(var(--color-tetsu-50))',
                    100: 'rgb(var(--color-tetsu-100))',
                    200: 'rgb(var(--color-tetsu-200))',
                    300: 'rgb(var(--color-tetsu-300))',
                    400: 'rgb(var(--color-tetsu-400))',
                    500: 'rgb(var(--color-tetsu-500))',
                    600: 'rgb(var(--color-tetsu-600))',
                    700: 'rgb(var(--color-tetsu-700))',
                    800: 'rgb(var(--color-tetsu-800))',
                    900: 'rgb(var(--color-tetsu-900))',
                },
                ishi: {
                    50: 'rgb(var(--color-ishi-50))',
                    100: 'rgb(var(--color-ishi-100))',
                    200: 'rgb(var(--color-ishi-200))',
                    300: 'rgb(var(--color-ishi-300))',
                    400: 'rgb(var(--color-ishi-400))',
                    500: 'rgb(var(--color-ishi-500))',
                    600: 'rgb(var(--color-ishi-600))',
                    700: 'rgb(var(--color-ishi-700))',
                    800: 'rgb(var(--color-ishi-800))',
                    900: 'rgb(var(--color-ishi-900))',
                },
            },
        },
    },
    plugins: [],
}
